# Generated by Django 4.1.7 on 2023-04-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('cabinet_no', models.IntegerField(primary_key=True, serialize=False)),
                ('cabinet_name', models.CharField(max_length=128)),
                ('cabinet_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Кабінет',
                'verbose_name_plural': 'Кабінети',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=20)),
                ('work_start_date', models.DateField()),
                ('image_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктори',
            },
        ),
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Категорія доктора',
                'verbose_name_plural': 'Категорії докторів',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('contract_num', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('street_type', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=40)),
                ('house_number', models.CharField(max_length=4)),
                ('flat_number', models.CharField(max_length=4)),
                ('post_index', models.IntegerField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor')),
            ],
            options={
                'verbose_name': 'Пацієнт',
                'verbose_name_plural': 'Пацієнти',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('cabinet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.cabinet')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.patient')),
            ],
            options={
                'verbose_name': 'Графік роботи',
                'verbose_name_plural': 'Графіки роботи',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_lastname', models.CharField(max_length=20)),
                ('commentator_name', models.CharField(max_length=20)),
                ('commentator_email', models.EmailField(max_length=254)),
                ('text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_complaint', models.CharField(max_length=255)),
                ('was_patient_present', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
            options={
                'verbose_name': 'Запис на прийом',
                'verbose_name_plural': 'Записи на прийом',
            },
        ),
        migrations.CreateModel(
            name='DoctorPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_value', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
            ],
            options={
                'verbose_name': 'Телефонний номер доктора',
                'verbose_name_plural': 'Телефонні номери докторів',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctorcategory'),
        ),
    ]
