# Generated by Django 4.1.5 on 2023-01-08 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='image_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 11, 23, 41, 918208, tzinfo=datetime.timezone.utc)),
        ),
    ]
