# Generated by Django 4.1.7 on 2023-04-11 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='commentator_email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='commentator_lastname',
        ),
        migrations.RemoveField(
            model_name='review',
            name='commentator_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.patient'),
        ),
    ]
