# Generated by Django 4.1.5 on 2023-01-08 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctors_image_name_alter_reviews_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinets',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 14, 46, 45, 974955, tzinfo=datetime.timezone.utc)),
        ),
    ]
