# Generated by Django 4.1.7 on 2023-04-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_doctor_lastname_en_doctor_lastname_uk_doctor_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='was_patient_present',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='url'),
        ),
    ]
