# Generated by Django 4.1.4 on 2023-01-13 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_cabinets_floor_alter_reviews_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 1, 13, 12, 50, 48, 970813, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_tm', models.DateTimeField(verbose_name='date_time')),
                ('is_busy', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cabinets',
            new_name='Cabinet',
        ),
        migrations.RenameModel(
            old_name='DoctorsCabinets',
            new_name='DoctorCabinet',
        ),
        migrations.RenameModel(
            old_name='DoctorCategories',
            new_name='DoctorCategory',
        ),
        migrations.RenameModel(
            old_name='PhoneNumbers',
            new_name='PhoneNumber',
        ),
        migrations.RenameModel(
            old_name='Recordings',
            new_name='Recording',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='person_id',
        ),
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='Persons',
            new_name='Person',
        ),
        migrations.DeleteModel(
            name='DoctorWorkingSchedule',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='WeekDays',
        ),
        migrations.AddField(
            model_name='schedule',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor'),
        ),
        migrations.AddField(
            model_name='review',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor'),
        ),
        migrations.AddField(
            model_name='review',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.person'),
        ),
    ]
