# Generated by Django 4.1.7 on 2023-05-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_recording_was_patient_present_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ('-cabinet_no',), 'verbose_name': 'Кабінет', 'verbose_name_plural': 'Кабінети'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('-work_start_date',), 'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктори'},
        ),
        migrations.AlterModelOptions(
            name='doctorcategory',
            options={'ordering': ['id'], 'verbose_name': 'Категорія доктора', 'verbose_name_plural': 'Категорії докторів'},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ('-created_at',), 'verbose_name': 'Запис на прийом', 'verbose_name_plural': 'Записи на прийом'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('created_at',), 'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('-start_datetime',), 'verbose_name': 'Графік роботи', 'verbose_name_plural': 'Графіки роботи'},
        ),
    ]
