# Generated by Django 4.1.4 on 2023-01-20 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_review_schedule_rename_cabinets_cabinet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='doctorcabinet',
            old_name='cabinet_id',
            new_name='cabinet',
        ),
        migrations.RenameField(
            model_name='doctorcabinet',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='recording',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='recording',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 11, 14, 10, 495858, tzinfo=datetime.timezone.utc)),
        ),
    ]
