# Generated by Django 4.1.4 on 2023-01-20 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_rename_category_id_doctor_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 11, 41, 52, 108984, tzinfo=datetime.timezone.utc)),
        ),
    ]
