# Generated by Django 4.1.7 on 2023-06-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_cabinet_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='patient',
        ),
        migrations.AddField(
            model_name='schedule',
            name='recording',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.recording'),
        ),
    ]
