# Generated by Django 4.1.4 on 2023-02-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_contractstatus_contractinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinfo',
            name='sign_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
