# Generated by Django 4.1.4 on 2023-02-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_contractinfo_sign_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractinfo',
            name='person_chat_id',
            field=models.BigIntegerField(),
        ),
    ]
